Algoritmo "SOMA2NUMEROS"

Var
// Seção de Declarações das variáveis

   A : inteiro
   B, C : inteiro

Inicio

      // fase entrada de dados

      // comando de saida
      escreva("Digite um número: ")
      
      // comando de entrada
      leia(A)
      
      escreva("Digite outro número: ")
      leia(B)
      
      // processamento
      C <- A + B
      
      // fase saida de dados
      escreva(C)

Fimalgoritmo